"""AI-powered (with honest static fallback) deep historical background for
a crisis. Kept because the new UI's Analysis sidebar still needs this real
logic ("extensive analysis of the event"), not because the old AI-tab UI
is coming back."""
import logging
import re
from datetime import datetime

from models import Session, Crisis, Relationship
from cache import cache_get, cache_set
from services.ai_client import anthropic_client, AI_MODEL

logger = logging.getLogger(__name__)

_ANALOGY_STRENGTHS = ('strong', 'moderate', 'loose')


def _parse_analogy_line(text):
    """Pull the single strongest historical parallel out of the model's
    response as one clean {match, strength, desc} record, without a
    JSON-parsing pipeline that would be fragile against prose containing
    stray braces or quotes. The prompt asks the model to end its response
    with exactly one line:
    "ANALOGY_MATCH: <name>|<strong|moderate|loose>|<one-sentence reason>" —
    this just finds that line and splits it. Any failure (missing line,
    wrong shape, an unrecognized strength word) returns None rather than
    guessing or returning a partial/garbled record — None flows straight
    into the existing "hide the analogy card" behavior, which is the
    correct fallback here, not a synthesized default.

    A qualitative strength word, not a 0-100 integer, is deliberate: no
    real precedent database or similarity metric backs this comparison,
    so a numeric "87% match" would be a fabricated precision the model
    invented on the spot. "strength" (not "pct") makes that impossible to
    mistake for one downstream.

    Returns (analogy_or_None, text_with_the_line_removed).
    """
    match = re.search(r'^ANALOGY_MATCH:\s*(.+)$', text, re.MULTILINE)
    if not match:
        return None, text

    cleaned_text = (text[:match.start()] + text[match.end():]).rstrip()
    parts = match.group(1).split('|', 2)
    if len(parts) != 3:
        return None, cleaned_text

    name, strength_raw, desc = (p.strip() for p in parts)
    strength = strength_raw.lower()
    if strength not in _ANALOGY_STRENGTHS:
        return None, cleaned_text
    if not name or not desc:
        return None, cleaned_text

    return {'match': name, 'strength': strength, 'desc': desc}, cleaned_text


def _format_history_disclaimer():
    """Appended to every deep-history response (AI or static) — this
    content is grounded in the model's general historical knowledge, not
    today's News rows the way the briefing's citations are, so unlike
    _format_sources_section there's no real source list to hand back.
    Being explicit about that distinction is the honest alternative to
    dressing this up with citations it doesn't actually have."""
    return ("\n\n## About This Analysis\n"
            "*This historical background and analogy were generated by AI from "
            "general historical knowledge, not sourced reporting on current news. "
            "Verify names, dates, and figures independently before citing them.*")


def _generate_static_history(crisis, relevant_relationships=None):
    """Rule-based fallback when no ANTHROPIC_API_KEY is set. There's no
    structured historical-narrative table in this app to synthesize a real
    timeline/background from — but there IS real, hand-curated Relationship
    data (see init_relationships in data_sources.py) for the specific pair
    of actors involved in this crisis when one resolves (see
    generate_deep_history's stakeholder-pair narrowing), so this states
    that real classification plainly (a fact, not a generated narrative).
    When no relevant pair resolves, this says exactly that — short and
    honest — rather than a multi-section skeleton padded with an AI-required
    disclaimer that used to appear even when real relationship facts WERE
    being shown. Also doesn't call _format_history_disclaimer(): that
    footer says "generated by AI", which is simply false on this path."""
    relevant_relationships = relevant_relationships or []

    if not relevant_relationships:
        return {
            'history': 'No history available.',
            'analogy': None,
            'model': 'static',
            'timestamp': datetime.utcnow().isoformat(),
        }

    facts = '\n'.join(
        f"- **{r.actor_a}–{r.actor_b}**: classified as *{r.label}* ({r.type}), "
        f"strength {r.strength}/100, stability {r.stability}/100"
        for r in relevant_relationships
    )
    text = (
        f"## Historical Background\n"
        f"This app's own curated data (real, hand-sourced from public alliance/treaty/conflict "
        f"records, not generated) classifies the following relationship(s) for the actors involved "
        f"in {crisis.title}:\n\n{facts}\n\n"
        f"## Timeline\n*No information available.*\n\n"
        f"## Historical Parallels\n*No information available.*"
    )
    return {
        'history': text,
        'analogy': None,
        'model': 'static',
        'timestamp': datetime.utcnow().isoformat(),
    }


def get_relevant_relationships(session, crisis):
    """Curated Relationship rows for the SPECIFIC pair of real actors involved
    in this crisis (both sides present in crisis.stakeholders). Fewer than 2
    stakeholders means no specific pair can be identified, so this returns []
    rather than a broad, mostly-irrelevant dump. Shared by the deep-history and
    scenarios features.

    Background (from when this was inline in generate_deep_history):
    # Real, hand-curated relationship data (NATO membership, active
    # wars, territorial disputes — see init_relationships in
    # data_sources.py) grounds the generated history in an actual
    # classification this app already carries, instead of leaving
    # Claude to work from general knowledge alone. Narrowed to the
    # SPECIFIC pair of real actors involved in this crisis (both sides
    # present in crisis.stakeholders — the real, word-boundary-matched
    # actor ids already written by _find_stakeholders() at ingest) —
    # not every relationship the crisis's single resolved country
    # happens to have. The single-actor resolution this used previously
    # (_resolve_crisis_actors, matching only the crisis's own country)
    # pulled that country's ENTIRE curated relationship roster regardless
    # of relevance to this specific crisis — confirmed the direct cause
    # of a real complaint: a crisis involving the US surfaced 14
    # unrelated US relationships (AU, NZ, PH, TW, SA, EG, QA, AE, JO, UA,
    # MX, CO, VE, CU) with no connection to what the crisis was actually
    # about. Fewer than 2 real stakeholders means no specific pair can
    # be identified — treated as "no relevant relationship" rather than
    # falling back to that broad, mostly-irrelevant dump.
    """
    stakeholder_ids = [s for s in (crisis.stakeholders or '').split(',') if s]
    if len(stakeholder_ids) < 2:
        return []
    return session.query(Relationship).filter(
        Relationship.is_active == True,
        Relationship.actor_a.in_(stakeholder_ids),
        Relationship.actor_b.in_(stakeholder_ids),
    ).all()


def generate_deep_history(crisis_id):
    """
    Generate AI-powered deep historical background, a dated timeline, and a
    historical-analogy match using Claude API. Cached for 48 hours — far
    longer than the briefing's 1 hour, since root historical causes and
    prior analogous crises don't change on the timescale a live situation
    briefing does, and regenerating this on every hourly refresh would just
    burn API cost for identical output.
    """
    cache_key = f"history:{crisis_id}"
    cached = cache_get(cache_key)
    if cached is not None:
        logger.info(f"[History] Cache hit for crisis {crisis_id}")
        return cached

    logger.info(f"[History] Cache miss for crisis {crisis_id} — generating via Claude API")

    session = Session()
    try:
        crisis = session.query(Crisis).filter(Crisis.id == crisis_id).first()
        if not crisis:
            return None

        relevant_relationships = get_relevant_relationships(session, crisis)
        relationship_facts = '\n'.join(
            f"- {r.actor_a}–{r.actor_b}: {r.type}, \"{r.label}\" (strength {r.strength}/100, stability {r.stability}/100)"
            for r in relevant_relationships
        ) or 'No curated relationship record exists for this crisis\'s actors.'

        # Deliberately minimal beyond that — history/root-causes/prior-
        # analogies don't depend on today's news, escalation trend, or
        # economic impact the way the current-situation briefing does;
        # pulling those in would blur this feature's purpose with the
        # briefing's.
        context = f"""
Crisis: {crisis.title}
Location: {crisis.country}
Type: {crisis.type}

Current Situation: {crisis.analysis}

This app's own curated relationship data for the actors involved (real, hand-sourced from public alliance/treaty/conflict records — ground your historical narrative in these classifications where they're relevant, rather than treating them as incidental):
{relationship_facts}
"""

        if anthropic_client and anthropic_client.api_key:
            try:
                message = anthropic_client.messages.create(
                    model=AI_MODEL,
                    max_tokens=3000,
                    messages=[
                        {
                            "role": "user",
                            "content": f"""Write a deep historical background briefing for this geopolitical crisis, for a journalist or researcher who needs to understand how this situation actually came to be — not what's happening today, but the decades (or longer) of history behind it. If the Crisis Context below includes a curated relationship record for the actors involved, treat it as a real, authoritative anchor — e.g. explicitly address how long that classified tension/alliance has existed and how today's crisis fits into it — rather than writing around it.

Format your response EXACTLY as follows (keep the headers):

## Historical Background
[500-700 words on the root causes, prior conflicts or treaties, and how this region or relationship arrived at today's crisis. Be specific — name the actual historical events, agreements, and turning points, not generic "tensions have existed for years" language.]

## Timeline
[6-10 bullet points, oldest to newest, each one real dated historical event that led toward today's crisis, formatted as "- **YEAR** — one-sentence description". This is background history, not the current crisis's day-to-day developments.]

## Historical Parallels
[2-3 real past crises or conflicts this one genuinely resembles, with an honest assessment of how strong each parallel actually is — including where the comparison breaks down, not just where it holds.]

After the three sections above, end your ENTIRE response with exactly one more line in this exact format, for whichever historical parallel from the section above is the single strongest match:
ANALOGY_MATCH: <name of the historical event>|<one word: strong, moderate, or loose>|<one sentence on why>

Do not add any text after that line. Do not repeat it earlier in your response.

Crisis Context:
{context}

Be specific and factual — this will be read by someone who wants real history, not vague generalization. If you are not confident about a specific date or figure, say so rather than inventing one."""
                        }
                    ]
                )

                raw_text = message.content[0].text
                analogy, history_text = _parse_analogy_line(raw_text)
                history_text += _format_history_disclaimer()

                result = {
                    'history': history_text,
                    'analogy': analogy,
                    'model': AI_MODEL,
                    'timestamp': datetime.utcnow().isoformat(),
                }
                # 48 hours: see function docstring for why this is much
                # longer-lived than the briefing's cache.
                cache_set(cache_key, result, ttl=172800)
                logger.info(f"[History] Cached deep history for crisis {crisis_id} (TTL 172800s)")
                return result
            except Exception as e:
                logger.error(f"AI deep history error: {e}")
                return None
        else:
            logger.info("ANTHROPIC_API_KEY not set — generating static history")
            result = _generate_static_history(crisis, relevant_relationships)
            if result:
                cache_set(cache_key, result, ttl=172800)
            return result
    finally:
        session.close()
