"""
Canonical countries (config/countries.json, generated by
scripts/build_countries.py).

Sources name countries every which way — "UK", "Korea, South", "Burma",
"DRC", "Congo, Democratic Republic of the", GDELT's CAMEO codes (RUS, ZAR),
and sample data even put city names ("Kyiv") in the country field. The
frontend's country filter compared those raw strings to the topojson's names
and silently missed. Everything now resolves to one record whose `code` is
the ISO 3166-1 numeric id the frontend topojson uses.
"""
import json
import os
import re
import unicodedata
from functools import lru_cache

_TABLE_PATH = os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))), 'config', 'countries.json'
)
_SHORT = 3  # aliases this short ("US", "UK", "DRC") match text case-sensitively


def _norm(text):
    text = unicodedata.normalize('NFKD', str(text)).encode('ascii', 'ignore').decode('ascii').lower()
    text = re.sub(r"[^a-z0-9' ]+", ' ', text.replace('.', ''))
    text = ' '.join(text.split())
    return text[4:] if text.startswith('the ') else text


@lru_cache(maxsize=1)
def _load():
    with open(_TABLE_PATH, 'r', encoding='utf-8') as f:
        countries = json.load(f)['countries']
    by_code = {c['code']: c for c in countries}
    by_name = {}
    by_iso3 = {}
    for c in countries:
        for alias in [c['name'], *c.get('aliases', []), c.get('iso2') or '', c.get('iso3') or '']:
            if alias:
                by_name.setdefault(_norm(alias), c['code'])
        for code in [c.get('iso3'), *c.get('iso3_aliases', [])]:
            if code:
                by_iso3[code.upper()] = c['code']
    return by_code, by_name, by_iso3


def by_code(code):
    return _load()[0].get(str(code)) if code else None


def resolve(name):
    """The canonical record for a country name/alias/ISO code, or None."""
    if not name:
        return None
    code = _load()[1].get(_norm(name))
    return by_code(code) if code else None


def from_iso3(code):
    """Record for a CAMEO/ISO alpha-3 code (GDELT actor country codes)."""
    if not code:
        return None
    resolved = _load()[2].get(str(code).strip().upper())
    return by_code(resolved) if resolved else None


@lru_cache(maxsize=1)
def _text_patterns():
    """(long_regex, short_regex, demonym_regex, lookup) for finding country
    mentions in free text. Long names are case-insensitive; short aliases
    (US, UK, UAE) must match exactly so "us" the pronoun never counts."""
    by_code_map = _load()[0]
    long_aliases, short_aliases, demonyms = {}, {}, {}
    for code, c in by_code_map.items():
        for alias in [c['name'], *c.get('aliases', [])]:
            if len(alias.replace('.', '')) <= _SHORT:
                if alias.isupper() or '.' in alias:
                    short_aliases[alias] = code
            else:
                long_aliases.setdefault(alias.lower(), code)
        for demonym in c.get('demonyms', []):
            demonyms.setdefault(demonym.lower(), code)

    def alternation(words):
        return '|'.join(re.escape(w) for w in sorted(words, key=len, reverse=True))

    long_re = re.compile(r'(?<![\w.])(?:' + alternation(long_aliases) + r')(?![\w])', re.IGNORECASE)
    short_re = re.compile(r'(?<![\w.])(?:' + alternation(short_aliases) + r')(?![\w])')
    demonym_re = re.compile(r'\b(?:' + alternation(demonyms) + r')s?\b', re.IGNORECASE)
    return long_re, short_re, demonym_re, long_aliases, short_aliases, demonyms


def find_in_text(text):
    """Country mentions in `text`: list of (code, start, end, kind) where
    kind is 'name' or 'demonym'. Longest match wins at each position."""
    if not text:
        return []
    long_re, short_re, demonym_re, long_aliases, short_aliases, demonyms = _text_patterns()
    found = []
    taken = set()
    for regex, lookup, kind, key in (
        (long_re, long_aliases, 'name', str.lower),
        (short_re, short_aliases, 'name', lambda s: s),
        (demonym_re, demonyms, 'demonym', lambda s: s.lower().rstrip('s') if s.lower().rstrip('s') in demonyms else s.lower()),
    ):
        for m in regex.finditer(text):
            span = range(m.start(), m.end())
            if any(i in taken for i in span):
                continue
            code = lookup.get(key(m.group(0)))
            if code:
                found.append((code, m.start(), m.end(), kind))
                taken.update(span)
    return sorted(found, key=lambda f: f[1])
